groups/urls.py
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns = [
    path('', views.ListGroups.as_view(), name = 'all'),
    path('new', views.CreateGroup.as_view(), name = 'create'),
    path('posts/<slug>', views.SingleGroup.as_view(), name = 'single'),
    path('join/<slug>', views.JoinGroup.as_view(), name = 'join'),
    path('leave/<slug>', views.LeaveGroup.as_view(), name = 'leave'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new', views.CreatePost.as_view(), name = 'create'),
    path('delete/<pk>', views.DeletePost.as_view(), name = 'delete'),
    path('<username>', views.UserPosts.as_view(), name = 'for_user'),
    path('<username>/<pk>', views.PostDetail.as_view(), name = 'single'),
]

spacesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Homepage.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')), # accounts urls
    path('accounts/', include('django.contrib.auth.urls')), # authorization
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('groups/', include('groups.urls', namespace = 'groups')),
    path('test', views.TestPage.as_view(), name = 'test'),
    path('thanks', views.ThanksPage.as_view(), name = 'thanks'),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
# Create your models here.
import misaka # allows use of markdown

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library() # for custom template tagging

class Group(models.Model):
    name = models.CharField(max_length = 255, unique = True)
    slug = models.SlugField(allow_unicode = True, unique = True)
    description = models.TextField(blank = True, default = '')
    description_html= models.TextField(editable = False, default = '', blank = True)
    members = models.ManyToManyField(User, through = 'GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs = {'slug': self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name = 'memberships', on_delete = models.CASCADE)
    user = models.ForeignKey(User, related_name = 'user_groups', on_delete = models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from typing import Any, Optional
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db import IntegrityError
from groups.models import Group, GroupMember
from . import models

# Create your views here.

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))
        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))
        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))
        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single',kwargs= {'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):

        try:
            membership = models.GroupMember.objects.filter(
                user = self.request.user,
                group__slug = self.kwargs.get('slug')).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry, you are not in this group')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group')
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    {% block pre_group %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block post_group %}{% endblock %}
  </div>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}

{% block pre_group %}

<h1>{{ group.name }}</h1>
<h2>Member Count: {{ group.members.count }}</h2>

<div class="content">
  {% if user in group.members.all %}
    <a class="btn btn-danger" href="{% url 'groups:leave' slug=group.slug %}">
      <i class="fa-solid fa-arrow-right-from-bracket" style="color: #ffffff;"></i> Leave
    </a>
  {% else %}
    <a class="btn btn-primary" href="{% url 'groups:join' slug=group.slug %}">
      <i class="fa-solid fa-arrow-right-to-bracket" style="color: #ffffff;"></i> Join
    </a>
  {% endif %}
</div>

{% endblock %}

{% block group_content %}

<div class="col-md-8">
  {% if group.posts.count == 0 %}
    <h2>There are no posts at the moment!</h2>
  {% else %}
    {% for post in group.posts.all %}
      {% include "posts/_post.html" %} <!--injecting a partial into content-->
    {% endfor %}
  {% endif %}
</div>

{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load django_bootstrap5 %}


{% block group_content %}

<h4>Create a new group!</h4>
<form class="form-control" action="{% url 'groups:create' %}" method='post' id='groupForm'>
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type="submit" class="'btn btn-primary" value="Create Group">
</form>

{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pre_group %}
<div class="col-md-4">
  <div class="content">
    {% if user.is_authenticated %}
    <h2>Welcome back
      <a href="{% url 'posts:for_user' username=user.username %}">
        @{{ user.username }}
      </a> <!-- links to user profile!-->
    </h2>
    {% endif %}
    <h2>Groups</h2>
    <p>Welcome to the Groups page!</p>
  </div>

  {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'groups:create' %}">
      <i class="fa-solid fa-plus" style="color: #ffffff;"></i> Create New Group!
    </a>
  {% endif %}
</div>
{% endblock %}


{% block group_content %}
  <div class="col-md-8">
    <div class="list-group">
      {% for group in object_list %} <!--list of all group objects, from generic list view-->
      <a class='list-group-item' href="{% url 'groups:single' slug=group.slug %}">
        <h3 class="title list-group-item-heading">{{ group.name }}</h3>
        <div class="list-group-item-text container-fluid">
          {{ group.description_html | safe }}
          <div class="row">
            <div class="col-md-4">
              <span class="badge">{{ group.members.count }}</span>
              member{{ group.members.count | pluralize }}
            </div>
            <div class="col-md-4">
              <span class="badge">{{ groups.posts.count }}</span>
              post{{ group.posts.count | pluralize }}
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
{% endblock %}