accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(template_name = 'accounts/login.html'), name = 'login'),
    path('logout', auth_views.LogoutView.as_view(), name = 'logout'),
    path('signup', views.SignUp.as_view(), name = 'signup'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name = 'all'),
    path('new', views.CreatePost.as_view(), name = 'create'),
    path('delete/<pk>', views.DeletePost.as_view(), name = 'delete'),
    path('<username>', views.UserPosts.as_view(), name = 'for_user'),
    path('<username>/<pk>', views.PostDetail.as_view(), name = 'single'),
]

spacesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Homepage.as_view(), name = 'home'),
    path('accounts/', include('accounts.urls', namespace = 'accounts')), # accounts urls
    path('accounts/', include('django.contrib.auth.urls')), # authorization
    path('posts/', include('posts.urls', namespace = 'posts')),
    path('groups/', include('groups.urls', namespace = 'groups')),
    path('test', views.TestPage.as_view(), name = 'test'),
    path('thanks', views.ThanksPage.as_view(), name = 'thanks'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Space Social</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'spacesocial/css/style.css'%}">
        <script src="https://kit.fontawesome.com/16ab03a688.js" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar mynav" role="navigation" id="navbar">
      <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Space Social</a>
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'posts:create' %}">Post</a></li>
            <li><a href="{% url 'groups:all' %}">Groups</a></li>
            <li><a href="{% url 'groups:create' %}">Create Group</a></li>
            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'groups:all' %}">Groups</a></li>
            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            <li><a href="{% url 'accounts:signup'%}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container mycontent">
      {% block content %}
      {% endblock %}
    </div>
  <canvas id="canvas"></canvas>
  </body>
  <script src="{% static 'spacesocial/js/master.js' %}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
  <h1> Welcome to the Starship Socialprise! </h1>
</div>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>You successfully logged in!</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visiting! Please come back soon!</h1>
{% endblock %}